ServerRoot "C:/laragon/bin/apache/httpd-2.4.66-260223-Win64-VS18"
ServerName localhost
Listen 127.0.0.1:4174

PidFile "C:/laragon/tmp/1g-sls-apache.pid"
ErrorLog "C:/laragon/tmp/1g-sls-apache-error.log"

LoadModule access_compat_module modules/mod_access_compat.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule setenvif_module modules/mod_setenvif.so

Include "C:/laragon/etc/apache2/mod_php.conf"

DocumentRoot "C:/laragon/www/1g-sls/public"

<Directory "C:/laragon/www/1g-sls/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<IfModule dir_module>
    DirectoryIndex index.php index.html
</IfModule>

<IfModule mime_module>
    TypesConfig conf/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>
