<?php

$everyFifteenMinutes = [];
$everyThirtyMinutes = [];

for ($hour = 0; $hour < 24; $hour++) {
    foreach ([0, 15, 30, 45] as $minute) {
        $everyFifteenMinutes[] = sprintf('%02d:%02d', $hour, $minute);
    }

    foreach ([0, 30] as $minute) {
        $everyThirtyMinutes[] = sprintf('%02d:%02d', $hour, $minute);
    }
}

return [
    'verify_ssl' => env('COUNTRY_INTEL_VERIFY_SSL', false),
    'gdelt_endpoint' => env('COUNTRY_INTEL_GDELT_ENDPOINT', 'https://api.gdeltproject.org/api/v2/doc/doc'),
    'gdelt_timespan' => env('COUNTRY_INTEL_GDELT_TIMESPAN', '30d'),
    'world_bank_procurement_endpoint' => env('WORLD_BANK_PROCUREMENT_ENDPOINT', 'https://search.worldbank.org/api/v2/procnotices'),
    'world_bank_recent_notice_days' => (int) env('WORLD_BANK_RECENT_NOTICE_DAYS', 45),
    'sam_gov_opportunities_endpoint' => env('SAM_GOV_OPPORTUNITIES_ENDPOINT', 'https://api.sam.gov/opportunities/v2/search'),
    'idb_procurement_endpoint' => env('IDB_PROCUREMENT_ENDPOINT', 'https://data.iadb.org/api/action/datastore_search'),
    'idb_procurement_resource_id' => env('IDB_PROCUREMENT_RESOURCE_ID', '856aabfd-2c6a-48fb-a8b8-19f3ff443618'),
    'ted_search_endpoint' => env('TED_SEARCH_ENDPOINT', 'https://api.ted.europa.eu/v3/notices/search'),
    'usaid_business_forecast_endpoint' => env('USAID_BUSINESS_FORECAST_ENDPOINT', 'https://data.usaid.gov/resource/qdtq-s66e.json'),
    'default_max_results' => (int) env('COUNTRY_INTEL_MAX_RESULTS', 10),
    'scheduled_max_results' => (int) env('COUNTRY_INTEL_SCHEDULED_MAX_RESULTS', 3),
    'max_queries_per_country' => (int) env('COUNTRY_INTEL_MAX_QUERIES_PER_COUNTRY', 16),
    'development_partner_max_queries_per_country' => (int) env('COUNTRY_INTEL_DONOR_MAX_QUERIES_PER_COUNTRY', 8),
    'donor_portal_source_limit' => (int) env('COUNTRY_INTEL_DONOR_PORTAL_SOURCE_LIMIT', 80),
    'global_sweep_gdelt_source_limit' => (int) env('COUNTRY_INTEL_GLOBAL_SWEEP_GDELT_SOURCE_LIMIT', 80),
    'global_sweep_portal_source_limit' => (int) env('COUNTRY_INTEL_GLOBAL_SWEEP_PORTAL_SOURCE_LIMIT', 80),
    'global_news_country_query_limit' => (int) env('COUNTRY_INTEL_GLOBAL_NEWS_COUNTRY_QUERY_LIMIT', 90),
    'news_recent_publication_days' => (int) env('COUNTRY_INTEL_NEWS_RECENT_PUBLICATION_DAYS', 90),
    'news_aggregator_queries_per_country' => (int) env('COUNTRY_INTEL_NEWS_AGGREGATOR_QUERIES_PER_COUNTRY', 6),
    'news_aggregator_results_per_query' => (int) env('COUNTRY_INTEL_NEWS_AGGREGATOR_RESULTS_PER_QUERY', 10),
    'news_aggregator_sources' => [
        [
            'name' => 'Google News RSS',
            'domain' => 'news.google.com',
            'url' => 'https://news.google.com/rss/search',
            'access_method' => 'google_news_rss',
            'connector' => 'google_news_rss',
        ],
        [
            'name' => 'Bing News RSS',
            'domain' => 'bing.com/news',
            'url' => 'https://www.bing.com/news/search?format=rss',
            'access_method' => 'bing_news_rss',
            'connector' => 'bing_news_rss',
        ],
    ],
    'source_discovery_terms' => [
        'en' => [
            'social security official',
            'social insurance official',
            'national insurance official',
            'pension fund official',
            'provident fund official',
            'retirement benefits authority',
            'ministry of labour official',
            'ministry of labor official',
            'ministry of social security',
            'ministry of social protection',
            'civil service commission',
            'public service commission',
            'ministry of public service',
            'government procurement portal',
            'public procurement portal',
            'federal procurement opportunities',
            'state procurement portal',
            'local government procurement portal',
            'city procurement bids',
            'county procurement bids',
        ],
        'fr' => [
            'caisse nationale de securite sociale',
            'securite sociale officiel',
            'caisse de retraite',
            'prevoyance sociale',
            'protection sociale',
            'ministere du travail',
            'ministere de la fonction publique',
            'fonction publique',
            'marches publics',
        ],
        'pt' => [
            'instituto nacional de seguranca social',
            'seguranca social oficial',
            'previdencia social',
            'fundo de pensoes',
            'ministerio do trabalho',
            'ministerio da administracao publica',
            'funcao publica',
            'contratacao publica',
        ],
        'ar' => [
            'الضمان الاجتماعي',
            'التأمينات الاجتماعية',
            'صندوق التقاعد',
            'صندوق المعاشات',
            'وزارة العمل',
            'وزارة الشؤون الاجتماعية',
            'الخدمة المدنية',
            'المشتريات الحكومية',
        ],
    ],
    'development_partner_sources' => [
        ['name' => 'World Bank Procurement', 'domain' => 'search.worldbank.org', 'url' => 'https://projects.worldbank.org/en/projects-operations/products-and-services/procurement-projects-programs', 'access_method' => 'official_api', 'connector' => 'world_bank'],
        ['name' => 'ILO Social Protection Project Pages', 'domain' => 'social-protection.org', 'url' => 'https://www.social-protection.org/gimi/Flagship.action', 'access_method' => 'indexed_search_fallback', 'connector' => 'ilo_social_protection_projects', 'registration_notes' => 'Monitor Contribution.action project pages through indexed search first because direct server-side fetching can be blocked by Cloudflare.'],
        ['name' => 'SAM.gov Contract Opportunities', 'domain' => 'sam.gov', 'url' => 'https://api.sam.gov/opportunities/v2/search', 'access_method' => 'official_api', 'connector' => 'sam_gov_opportunities'],
        ['name' => 'GSA Open APIs', 'domain' => 'open.gsa.gov', 'url' => 'https://open.gsa.gov/api/', 'access_method' => 'official_api_directory', 'connector' => 'gsa_api_directory'],
        ['name' => 'DevelopmentAid Tenders', 'domain' => 'developmentaid.org', 'url' => 'https://www.developmentaid.org/tenders/', 'access_method' => 'aggregator_portal', 'connector' => 'portal_html'],
        ['name' => 'Assortis Tender Opportunities', 'domain' => 'assortis.com', 'url' => 'https://www.assortis.com/', 'access_method' => 'aggregator_portal_api_check', 'connector' => 'assortis_portal', 'extra_urls' => ['https://www.assortis.com/tpl/organisations-daily-projects-alerts.asp']],
        ['name' => 'TendersGo', 'domain' => 'tendersgo.com', 'url' => env('TENDERSGO_PORTAL_URL', 'https://tendersgo.com/'), 'access_method' => 'api_credentials_required', 'connector' => 'tendersgo_api'],
        ['name' => 'Norwegian Refugee Council Procurement', 'domain' => 'nrc.no', 'url' => 'https://www.nrc.no/procurement/', 'access_method' => 'official_portal', 'connector' => 'portal_html', 'procurement_portal_type' => 'ngo'],
        ['name' => 'Catholic Relief Services Procurement', 'domain' => 'crs.org', 'url' => 'https://www.crs.org/', 'access_method' => 'site_pdf_crawler', 'connector' => 'portal_html', 'procurement_portal_type' => 'ngo', 'registration_notes' => 'CRS procurement opportunities are often published as country/program PDF notices rather than a single global tender index. Monitor CRS site pages and PDFs for procurement/RFP/tender terms.'],
        ['name' => 'Danish Refugee Council Tenders', 'domain' => 'drc.ngo', 'url' => 'https://drc.ngo/en/tenders/', 'access_method' => 'official_portal', 'connector' => 'portal_html', 'procurement_portal_type' => 'ngo', 'extra_urls' => ['https://drc.ngo/tenders/']],
        ['name' => 'African Development Bank Procurement', 'domain' => 'afdb.org', 'url' => 'https://www.afdb.org/en/about-us/corporate-procurement/procurement-notices/current-solicitations?sort=asc', 'access_method' => 'official_xml_feed', 'connector' => 'afdb_procurement', 'extra_urls' => ['https://www.afdb.org/en/about-us/corporate-procurement/procurement-notices/current-solicitations.xml']],
        ['name' => 'Asian Development Bank Business Opportunities', 'domain' => 'adb.org', 'url' => 'https://www.adb.org/business/project-procurement/business-opportunities', 'access_method' => 'official_portal', 'connector' => 'adb_procurement', 'extra_urls' => ['https://www.adb.org/business/institutional-procurement/notices']],
        ['name' => 'Inter-American Development Bank Procurement', 'domain' => 'iadb.org', 'url' => 'https://data.iadb.org/dataset/project-procurement-bidding-notices-and-notification-of-contract-awards', 'access_method' => 'official_api', 'connector' => 'idb_procurement'],
        ['name' => 'Caribbean Development Bank Procurement', 'domain' => 'caribank.org', 'url' => 'https://www.caribank.org/work-with-us/procurement', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'European Union TED', 'domain' => 'ted.europa.eu', 'url' => 'https://ted.europa.eu/', 'access_method' => 'official_api', 'connector' => 'ted'],
        ['name' => 'European Commission Funding and Tenders', 'domain' => 'ec.europa.eu', 'url' => 'https://api.tech.ec.europa.eu/search-api/prod/rest/search?apiKey=SEDIA', 'access_method' => 'official_api', 'connector' => 'ec_funding_tenders'],
        ['name' => 'EU International Partnerships', 'domain' => 'international-partnerships.ec.europa.eu', 'url' => 'https://api.tech.ec.europa.eu/search-api/prod/rest/search?apiKey=SEDIA', 'access_method' => 'official_api', 'connector' => 'ec_funding_tenders'],
        ['name' => 'European Bank for Reconstruction and Development Procurement', 'domain' => 'ecepp.ebrd.com', 'url' => 'https://ecepp.ebrd.com/delta/noticeSearchResults.html', 'access_method' => 'official_html_table', 'connector' => 'ebrd_ecepp'],
        ['name' => 'European Investment Bank Procurement', 'domain' => 'eib.org', 'url' => 'https://www.eib.org/provider-eib/app/list/medias/procurements', 'access_method' => 'official_json_endpoint', 'connector' => 'eib_procurement'],
        ['name' => 'GIZ Tender Opportunities', 'domain' => 'giz.de', 'url' => 'https://ausschreibungen.giz.de/', 'access_method' => 'official_portal', 'connector' => 'giz_procurement', 'extra_urls' => ['https://www.giz.de/de/partner/auftragnehmer/ausschreibungen']],
        ['name' => 'KfW Development Bank Procurement', 'domain' => 'gtai.de', 'url' => 'https://www.gtai.de/kfw-tender', 'access_method' => 'official_portal_indexed_fallback', 'connector' => 'kfw_gtai_search'],
        ['name' => 'Norad Grants and Procurement', 'domain' => 'norad.no', 'url' => 'https://www.norad.no/en/front/funding/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Nordic Development Fund Procurement', 'domain' => 'ndf.int', 'url' => 'https://www.ndf.int/work-with-us/procurement.html', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Sida Procurement and Grants', 'domain' => 'sida.se', 'url' => 'https://www.sida.se/en/for-partners/procurement', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Netherlands Enterprise Agency', 'domain' => 'rvo.nl', 'url' => 'https://english.rvo.nl/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'TenderNed Netherlands Procurement', 'domain' => 'tenderned.nl', 'url' => 'https://www.tenderned.nl/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'FMO Dutch Entrepreneurial Development Bank', 'domain' => 'fmo.nl', 'url' => 'https://www.fmo.nl/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Agence Francaise de Developpement Procurement', 'domain' => 'afd.fr', 'url' => 'https://www.afd.fr/en/responding-bid-invitation', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Expertise France Procurement', 'domain' => 'expertisefrance.fr', 'url' => 'https://www.expertisefrance.fr/en/tenders', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Enabel Procurement', 'domain' => 'enabel.be', 'url' => 'https://www.enabel.be/procurement/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'FCDO Development Tracker', 'domain' => 'devtracker.fcdo.gov.uk', 'url' => 'https://devtracker.fcdo.gov.uk/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'USAID Business Forecast and Opportunities', 'domain' => 'usaid.gov', 'url' => 'https://www.usaid.gov/business-forecast', 'access_method' => 'official_api', 'connector' => 'usaid_business_forecast'],
        ['name' => 'Millennium Challenge Corporation Procurement', 'domain' => 'mcc.gov', 'url' => 'https://www.mcc.gov/work-with-us/procurements', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'UN Development Programme Procurement', 'domain' => 'undp.org', 'url' => 'https://procurement-notices.undp.org/', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'UNGM Tender Portal', 'domain' => 'ungm.org', 'url' => 'https://www.ungm.org/Public/Notice', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
        ['name' => 'Islamic Development Bank Procurement', 'domain' => 'isdb.org', 'url' => 'https://www.isdb.org/project-procurement', 'access_method' => 'official_portal', 'connector' => 'portal_html'],
    ],
    'daily_batch_size' => (int) env('COUNTRY_INTEL_DAILY_BATCH_SIZE', 1),
    'ilo_social_protection_project_terms' => [
        'social protection',
        'social security',
        'social insurance',
        'pension',
        'pensions',
        'digital transformation',
        'digitalization',
        'digitization',
        'social registry',
        'beneficiary registry',
        'management information system',
        'payment system',
        'employment injury',
    ],
    'ilo_social_protection_project_weekly_time' => env('ILO_SOCIAL_PROTECTION_PROJECT_WEEKLY_TIME', '04:35'),
    'ilo_social_protection_project_weekly_country_limit' => (int) env('ILO_SOCIAL_PROTECTION_PROJECT_WEEKLY_COUNTRY_LIMIT', 25),
    'ilo_social_protection_project_queries_per_country' => (int) env('ILO_SOCIAL_PROTECTION_PROJECT_QUERIES_PER_COUNTRY', 3),
    'ilo_social_protection_project_results_per_query' => (int) env('ILO_SOCIAL_PROTECTION_PROJECT_RESULTS_PER_QUERY', 5),
    'daily_slots' => $everyFifteenMinutes,
    'hrms_tender_slots' => $everyThirtyMinutes,
    'sector_tender_slots' => [
        '00:15',
        '00:45',
        '01:15',
        '01:45',
        '02:15',
        '02:45',
        '03:15',
        '03:45',
        '04:15',
        '04:45',
        '05:15',
        '05:45',
        '06:15',
        '06:45',
        '07:15',
        '07:45',
        '08:15',
        '08:45',
        '09:15',
        '09:45',
        '10:15',
        '10:45',
        '11:15',
        '11:45',
        '12:15',
        '12:45',
        '13:15',
        '13:45',
        '14:15',
        '14:45',
        '15:15',
        '15:45',
        '16:15',
        '16:45',
        '17:15',
        '17:45',
        '18:15',
        '18:45',
        '19:15',
        '19:45',
        '20:15',
        '20:45',
        '21:15',
        '21:45',
        '22:15',
        '22:45',
        '23:15',
        '23:45',
    ],

    'focuses' => [
        'social_security' => [
            'label' => 'Social Security Intelligence',
            'description' => 'Social security, social protection, pensions, provident funds, labour ministry, procurement, and tender updates.',
            'terms' => [
                'social security',
                'social security benefit',
                'social security benefits',
                'social security administration system',
                'social security board',
                'social insurance',
                'social insurance benefit',
                'social insurance benefits',
                'social insurance information system',
                'national insurance',
                'national insurance benefit',
                'national insurance benefits',
                'national insurance information system',
                'abssb',
                'social protection',
                'social protection system',
                'social protection systems',
                'social protection programme',
                'social protection program',
                'adaptive social protection',
                'protection sociale',
                'securite sociale',
                'seguridad social',
                'seguranca social',
                'previdencia social',
                'pensions',
                'pension',
                'pension reform',
                'pension payment',
                'pension payments',
                'pension increase',
                'pension arrears',
                'old age pension',
                'retirement',
                'retirement benefits',
                'retraite',
                'ipres',
                'lipres',
                'nssf',
                'cnss',
                'inss',
                'caisse de securite sociale',
                'pension administration',
                'pension administration system',
                'pension management information system',
                'pension information system',
                'provident fund',
                'provident funds',
                'provident fund reform',
                'provident fund system',
                'beneficiary registry',
                'beneficiary registration',
                'benefit payment system',
                'contribution',
                'contributions',
                'contribution rate',
                'contribution rates',
                'benefit payments',
                'benefits administration',
                'ministry of labor',
                'ministry of labour',
                'tender',
                'tenders',
                'procurement',
                'rfp',
                'request for proposal',
                'expression of interest',
            ],
            'strong_signals' => ['ipres', 'lipres', 'css', 'abssb', 'nssf', 'cnss', 'inss', 'socialsecurity.gov.ag', 'secusociale', 'dgtss', 'travail.gouv'],
        ],

        'hrms_tenders' => [
            'label' => 'HRMS Tender Intelligence',
            'description' => 'Tender and RFP opportunities for HRMS, payroll, benefits administration, talent management, employee performance management, human resources management, HRMIS, HRIMS, and HCM systems in target industries.',
            'terms' => [
                'hrms',
                'hcm',
                'payroll',
                'human resources management',
                'human resource management',
                'human capital management',
                'human resources information system',
                'human resource information system',
                'human resource management system',
                'human resources management system',
                'personnel management system',
                'personnel information system',
                'civil service management system',
                'integrated personnel payroll',
                'integrated payroll and personnel',
                'hrmis',
                'hrims',
                'workforce management',
                'employee self service',
                'employee self-service',
                'personnel management system',
                'talent management',
                'employee performance management',
                'learning management system',
                'benefits administration',
                'time and attendance',
                'higher education',
                'university',
                'college',
                'telecom',
                'telecommunications',
                'oil and gas',
                'petroleum',
                'government',
                'civil service',
                'public service',
                'public administration',
                'postal service',
                'postal services',
                'post office',
                'healthcare',
                'health care',
                'hospital',
                'ministry of health',
                'request for proposal',
                'expression of interest',
                'tender',
                'procurement',
                'rfp',
                'bid',
            ],
            'strong_signals' => ['hrms', 'hcm', 'payroll', 'hrmis', 'hrims', 'human resource', 'human resources', 'workforce management', 'benefits administration', 'talent management', 'employee performance management'],
            'industry_contexts' => [
                'higher education',
                'university',
                'college',
                'telecom',
                'telecommunications',
                'oil and gas',
                'petroleum',
                'government',
                'civil service',
                'public service',
                'public administration',
                'postal service',
                'postal services',
                'post office',
                'healthcare',
                'health care',
                'hospital',
                'ministry of health',
            ],
        ],

        'erms_tenders' => [
            'label' => 'ERMS Tender Intelligence',
            'description' => 'Tender and RFP opportunities for enterprise risk management, risk management software, GRC, compliance, audit, controls, and operational risk systems.',
            'terms' => [
                'risk management software',
                'enterprise risk management',
                'enterprise risk management system',
                'erm software',
                'erms',
                'risk management information system',
                'risk assessment software',
                'risk register',
                'risk register software',
                'governance risk compliance',
                'governance risk and compliance',
                'grc software',
                'compliance management system',
                'audit management system',
                'internal audit software',
                'internal controls',
                'control self assessment',
                'operational risk management',
                'incident management system',
                'loss event database',
                'risk analytics',
            ],
            'strong_signals' => ['risk management software', 'enterprise risk management', 'erm software', 'erms', 'grc software', 'risk register', 'compliance management system', 'audit management system', 'operational risk management'],
        ],

        'ebpc_tenders' => [
            'label' => 'EBPC Tender Intelligence',
            'description' => 'Tender and RFP opportunities for budgeting software, budget planning, budget preparation, budget control, forecasting, and public-sector budget management systems.',
            'terms' => [
                'budgeting software',
                'budget planning software',
                'budget preparation software',
                'budget control software',
                'budget management system',
                'budget management information system',
                'integrated financial management information system',
                'financial management information system',
                'ifmis',
                'fmis',
                'pfmis',
                'public financial management information system',
                'budget preparation system',
                'budget formulation system',
                'budget execution system',
                'budget monitoring system',
                'budget planning system',
                'budget and planning system',
                'budget module',
                'budget preparation module',
                'budget execution module',
                'program based budgeting',
                'programme based budgeting',
                'performance based budgeting',
                'financial planning software',
                'financial planning and analysis',
                'fp&a software',
                'forecasting software',
                'planning budgeting forecasting',
                'performance budgeting',
                'program budgeting',
                'public financial management system',
                'medium term expenditure framework',
                'mtef',
                'request for proposal',
                'expression of interest',
                'tender',
                'procurement',
                'rfp',
                'bid',
            ],
            'strong_signals' => ['budgeting software', 'budget planning', 'budget preparation', 'budget control', 'budget management system', 'budget formulation', 'budget execution', 'integrated financial management information system', 'ifmis', 'fmis', 'public financial management system', 'financial planning software', 'forecasting software'],
        ],

        'sector_tenders' => [
            'label' => 'Sector Tender Intelligence',
            'description' => 'Tender and RFP opportunities for telecom, oil and gas, postal services, civil service and public administration, airlines and aviation, mining, banking, and finance.',
            'terms' => [
                'telecom',
                'telecommunications',
                'mobile network',
                'broadband',
                'fiber optic',
                'fibre optic',
                'ict infrastructure',
                'oil and gas',
                'petroleum',
                'natural gas',
                'lng',
                'pipeline',
                'postal services',
                'postal service',
                'post office',
                'mail service',
                'civil service',
                'public service',
                'public administration',
                'government administration',
                'airline',
                'airlines',
                'aviation',
                'airport',
                'civil aviation',
                'mining',
                'minerals',
                'mineral resources',
                'banking',
                'bank',
                'finance',
                'financial services',
                'central bank',
                'treasury',
                'tax administration',
                'customs',
                'request for proposal',
                'request for proposals',
                'expression of interest',
                'request for expressions of interest',
                'request for bids',
                'invitation for bids',
                'tender',
                'tenders',
                'procurement',
                'rfp',
                'bid',
                'bids',
                'contract notice',
            ],
            'strong_signals' => [
                'telecom',
                'telecommunications',
                'oil and gas',
                'petroleum',
                'postal',
                'civil service',
                'public administration',
                'airline',
                'aviation',
                'airport',
                'mining',
                'banking',
                'financial services',
                'central bank',
            ],
        ],
    ],

    'localized_country_names' => [
        'DZ' => ['الجزائر'],
        'BH' => ['البحرين'],
        'EG' => ['مصر'],
        'IQ' => ['العراق'],
        'JO' => ['الأردن'],
        'KW' => ['الكويت'],
        'LB' => ['لبنان'],
        'LY' => ['ليبيا'],
        'MA' => ['المغرب'],
        'MR' => ['موريتانيا'],
        'OM' => ['عمان'],
        'PS' => ['فلسطين'],
        'QA' => ['قطر'],
        'SA' => ['السعودية', 'المملكة العربية السعودية'],
        'SD' => ['السودان'],
        'SY' => ['سوريا'],
        'TN' => ['تونس'],
        'AE' => ['الإمارات', 'الإمارات العربية المتحدة'],
        'YE' => ['اليمن'],
        'CN' => ['中国'],
        'JP' => ['日本'],
        'KR' => ['대한민국', '한국'],
        'TH' => ['ประเทศไทย'],
        'VN' => ['Việt Nam'],
        'ID' => ['Indonesia'],
        'MY' => ['Malaysia'],
        'TR' => ['Türkiye'],
        'IR' => ['ایران'],
        'PK' => ['پاکستان'],
        'BD' => ['বাংলাদেশ'],
        'IN' => ['भारत'],
    ],

    'localized_focus_terms' => [
        'sector_tenders' => [
            'ar' => [
                'مناقصة', 'مناقصات', 'عطاء', 'عطاءات', 'شراء', 'مشتريات', 'طلب عروض',
                'اتصالات', 'نفط وغاز', 'النفط والغاز', 'خدمات بريدية', 'البريد',
                'الخدمة المدنية', 'الإدارة العامة', 'طيران', 'مطارات', 'تعدين',
                'مصارف', 'بنوك', 'خدمات مالية', 'البنك المركزي',
            ],
            'zh' => [
                '招标', '采购', '投标', '征求建议书', '电信', '石油天然气', '邮政服务',
                '公务员', '公共行政', '航空', '机场', '采矿', '银行', '金融服务', '中央银行',
            ],
            'ja' => [
                '入札', '調達', '提案依頼', '電気通信', '石油ガス', '郵便サービス',
                '公務員', '行政', '航空', '空港', '鉱業', '銀行', '金融サービス', '中央銀行',
            ],
            'ko' => [
                '입찰', '조달', '제안요청서', '통신', '석유 가스', '우편 서비스',
                '공무원', '공공 행정', '항공', '공항', '광업', '은행', '금융 서비스', '중앙은행',
            ],
            'th' => [
                'ประกวดราคา', 'จัดซื้อจัดจ้าง', 'โทรคมนาคม', 'น้ำมันและก๊าซ', 'ไปรษณีย์',
                'ข้าราชการ', 'การบริหารราชการ', 'การบิน', 'สนามบิน', 'เหมืองแร่', 'ธนาคาร', 'การเงิน',
            ],
            'vi' => [
                'đấu thầu', 'mua sắm', 'viễn thông', 'dầu khí', 'dịch vụ bưu chính',
                'công vụ', 'hành chính công', 'hàng không', 'sân bay', 'khai khoáng', 'ngân hàng', 'tài chính',
            ],
            'id' => [
                'tender', 'pengadaan', 'telekomunikasi', 'minyak dan gas', 'layanan pos',
                'pegawai negeri', 'administrasi publik', 'penerbangan', 'bandara', 'pertambangan', 'perbankan', 'keuangan',
            ],
            'ms' => [
                'tender', 'perolehan', 'telekomunikasi', 'minyak dan gas', 'perkhidmatan pos',
                'perkhidmatan awam', 'pentadbiran awam', 'penerbangan', 'lapangan terbang', 'perlombongan', 'perbankan', 'kewangan',
            ],
            'tr' => [
                'ihale', 'satın alma', 'telekom', 'telekomünikasyon', 'petrol ve gaz', 'posta hizmetleri',
                'kamu hizmeti', 'kamu yönetimi', 'havacılık', 'havaalanı', 'madencilik', 'bankacılık', 'finans',
            ],
            'fa' => [
                'مناقصه', 'تدارکات', 'مخابرات', 'نفت و گاز', 'خدمات پستی',
                'خدمات ملکی', 'اداره عامه', 'هوانوردی', 'فرودگاه', 'معدن', 'بانکداری', 'مالی',
            ],
            'ur' => [
                'ٹینڈر', 'خریداری', 'ٹیلی کام', 'تیل اور گیس', 'ڈاک خدمات',
                'سول سروس', 'عوامی انتظامیہ', 'ایوی ایشن', 'ہوائی اڈہ', 'کان کنی', 'بینکاری', 'مالیات',
            ],
            'bn' => [
                'দরপত্র', 'ক্রয়', 'টেলিকম', 'তেল ও গ্যাস', 'ডাক সেবা',
                'সিভিল সার্ভিস', 'জনপ্রশাসন', 'বিমান চলাচল', 'বিমানবন্দর', 'খনি', 'ব্যাংকিং', 'অর্থ',
            ],
            'hi' => [
                'निविदा', 'खरीद', 'दूरसंचार', 'तेल और गैस', 'डाक सेवा',
                'सिविल सेवा', 'लोक प्रशासन', 'विमानन', 'हवाई अड्डा', 'खनन', 'बैंकिंग', 'वित्त',
            ],
        ],
        'social_security' => [
            'ar' => ['الضمان الاجتماعي', 'التأمينات الاجتماعية', 'التقاعد', 'المعاشات', 'وزارة العمل', 'الحماية الاجتماعية', 'مناقصة', 'مشتريات'],
            'fr' => ['securite sociale', 'sécurité sociale', 'retraite', 'pension', 'protection sociale', 'ministere du travail', 'appel d offres'],
            'de' => ['soziale sicherheit', 'sozialversicherung', 'rente', 'pension', 'alterssicherung', 'sozialschutz', 'arbeitsministerium', 'ausschreibung', 'vergabe'],
            'nl' => ['sociale zekerheid', 'sociale verzekering', 'pensioen', 'pensioenen', 'pensioenadministratie', 'ministerie van sociale zaken', 'aanbesteding', 'overheidsopdracht'],
            'it' => ['sicurezza sociale', 'previdenza sociale', 'pensione', 'pensioni', 'protezione sociale', 'ministero del lavoro', 'gara', 'appalto'],
            'pl' => ['ubezpieczenie spoleczne', 'zabezpieczenie spoleczne', 'emerytura', 'emerytury', 'ministerstwo pracy', 'zamowienie publiczne', 'przetarg'],
            'sv' => ['social trygghet', 'socialforsakring', 'pension', 'pensioner', 'arbetsmarknadsdepartementet', 'upphandling', 'anbud'],
            'da' => ['social sikring', 'socialforsikring', 'pension', 'pensioner', 'beskaeftigelsesministeriet', 'udbud', 'offentligt udbud'],
            'fi' => ['sosiaaliturva', 'sosiaalivakuutus', 'elake', 'elakkeet', 'julkinen hankinta', 'tarjouskilpailu'],
            'no' => ['trygd', 'sosial sikkerhet', 'pensjon', 'pensjoner', 'anskaffelse', 'anbud'],
            'cs' => ['socialni zabezpeceni', 'socialni pojisteni', 'duchod', 'duchody', 'verejna zakazka', 'vyberove rizeni'],
            'es' => [
                'seguridad social',
                'seguro social',
                'proteccion social',
                'sistema de proteccion social',
                'prevision social',
                'pensiones',
                'pension',
                'reforma de pensiones',
                'pago de pensiones',
                'beneficios de pension',
                'jubilacion',
                'prestaciones sociales',
                'subsidios',
                'cotizaciones',
                'aportes',
                'afiliados',
                'beneficiarios',
                'ministerio de trabajo',
                'ministerio del trabajo',
                'licitacion',
                'contratacion publica',
                'compras publicas',
                'convocatoria',
                'concurso publico',
                'expresion de interes',
            ],
            'pt' => [
                'seguranca social',
                'previdencia social',
                'protecao social',
                'sistema de protecao social',
                'pensao',
                'pensoes',
                'aposentadoria',
                'reforma da previdencia',
                'pagamento de pensoes',
                'beneficios previdenciarios',
                'beneficios sociais',
                'contribuicoes',
                'segurados',
                'beneficiarios',
                'ministerio do trabalho',
                'licitacao',
                'contratacao publica',
                'compras publicas',
                'concurso publico',
                'manifestacao de interesse',
            ],
        ],
        'hrms_tenders' => [
            'ar' => ['نظام الموارد البشرية', 'الرواتب', 'إدارة الموارد البشرية', 'مناقصة', 'مشتريات'],
            'fr' => ['ressources humaines', 'paie', 'systeme de gestion des ressources humaines', 'appel d offres'],
            'de' => ['personalmanagement', 'personalverwaltung', 'hr software', 'hrms', 'gehaltsabrechnung', 'lohnabrechnung', 'ausschreibung', 'vergabe'],
            'nl' => ['personeelszaken', 'hr software', 'hrms', 'salarisadministratie', 'personeelsadministratie', 'aanbesteding', 'overheidsopdracht'],
            'it' => ['risorse umane', 'software hr', 'gestione del personale', 'paghe', 'gara', 'appalto'],
            'pl' => ['zarzadzanie zasobami ludzkimi', 'hrms', 'kadry', 'place', 'system kadrowy', 'zamowienie publiczne', 'przetarg'],
            'sv' => ['hr system', 'personaladministration', 'loner', 'lonesystem', 'upphandling', 'anbud'],
            'da' => ['hr system', 'personaleadministration', 'lon', 'lonsystem', 'udbud', 'anskaffelse'],
            'fi' => ['hr jarjestelma', 'henkilostohallinto', 'palkanlaskenta', 'hankinta', 'tarjouskilpailu'],
            'es' => [
                'recursos humanos',
                'nomina',
                'sistema de gestion de recursos humanos',
                'sistema de informacion de recursos humanos',
                'gestion del talento',
                'gestion de talento',
                'gestion del desempeno',
                'evaluacion del desempeno',
                'administracion de beneficios',
                'control de asistencia',
                'tiempo y asistencia',
                'autoservicio del empleado',
                'gestion de personal',
                'capital humano',
                'licitacion',
                'contratacion publica',
                'compras publicas',
                'expresion de interes',
            ],
            'pt' => [
                'recursos humanos',
                'folha de pagamento',
                'sistema de gestao de recursos humanos',
                'sistema de informacao de recursos humanos',
                'gestao de talentos',
                'gestao de desempenho',
                'avaliacao de desempenho',
                'administracao de beneficios',
                'controle de frequencia',
                'ponto eletronico',
                'autosservico do empregado',
                'gestao de pessoal',
                'capital humano',
                'licitacao',
                'contratacao publica',
                'compras publicas',
                'manifestacao de interesse',
            ],
        ],
        'erms_tenders' => [
            'fr' => ['gestion des risques', 'logiciel de gestion des risques', 'conformite', 'audit interne', 'controle interne', 'registre des risques', 'appel d offres'],
            'de' => ['risikomanagement', 'risikomanagement software', 'grc software', 'compliance management', 'interne revision', 'risikoregister', 'ausschreibung', 'vergabe'],
            'nl' => ['risicomanagement', 'risicomanagement software', 'grc software', 'compliance management', 'interne audit', 'risicoregister', 'aanbesteding'],
            'it' => ['gestione dei rischi', 'software gestione rischi', 'grc', 'conformita', 'audit interno', 'registro rischi', 'gara', 'appalto'],
            'pl' => ['zarzadzanie ryzykiem', 'oprogramowanie do zarzadzania ryzykiem', 'grc', 'compliance', 'audyt wewnetrzny', 'rejestr ryzyka', 'przetarg'],
            'es' => ['gestion de riesgos', 'software de gestion de riesgos', 'sistema de gestion de riesgos', 'riesgo operativo', 'cumplimiento', 'auditoria interna', 'controles internos', 'registro de riesgos', 'licitacion', 'contratacion publica'],
            'pt' => ['gestao de riscos', 'software de gestao de riscos', 'sistema de gestao de riscos', 'risco operacional', 'conformidade', 'auditoria interna', 'controles internos', 'registro de riscos', 'licitacao', 'contratacao publica'],
        ],
        'ebpc_tenders' => [
            'fr' => ['logiciel budgetaire', 'systeme budgetaire', 'planification budgetaire', 'controle budgetaire', 'gestion budgetaire', 'planification financiere', 'appel d offres'],
            'de' => ['budget software', 'budgetplanung', 'budgetkontrolle', 'haushaltsplanung', 'finanzplanung', 'ausschreibung', 'vergabe'],
            'nl' => ['budget software', 'budgetplanning', 'budgetbeheer', 'begrotingssysteem', 'financiele planning', 'aanbesteding'],
            'it' => ['software di bilancio', 'pianificazione di bilancio', 'controllo di bilancio', 'gestione del budget', 'pianificazione finanziaria', 'gara', 'appalto'],
            'pl' => ['oprogramowanie budzetowe', 'planowanie budzetu', 'kontrola budzetu', 'zarzadzanie budzetem', 'planowanie finansowe', 'przetarg'],
            'es' => ['software de presupuesto', 'sistema presupuestario', 'sistema de presupuesto', 'formulacion presupuestaria', 'planificacion presupuestaria', 'control presupuestario', 'gestion presupuestaria', 'planificacion financiera', 'licitacion', 'contratacion publica'],
            'pt' => ['software de orcamento', 'sistema orcamentario', 'sistema de orcamento', 'formulacao orcamentaria', 'planejamento orcamentario', 'controle orcamentario', 'gestao orcamentaria', 'planejamento financeiro', 'licitacao', 'contratacao publica'],
        ],
    ],

    'topics' => [
        'social security',
        'social security board',
        'social insurance',
        'national insurance',
        'abssb',
        'social protection',
        'protection sociale',
        'securite sociale',
        'securité sociale',
        'sécurité sociale',
        'seguridad social',
        'seguranca social',
        'previdencia social',
        'pensions',
        'pension',
        'pension reform',
        'pension payment',
        'pension payments',
        'retirement',
        'retirement benefits',
        'retraite',
        'ipres',
        'lipres',
        'nssf',
        'cnss',
        'inss',
        'caisse de securite sociale',
        'caisse de sécurité sociale',
        'pension administration',
        'provident fund',
        'provident funds',
        'contribution',
        'contributions',
        'benefit payments',
        'ministry of labor',
        'ministry of labour',
        'tenders',
        'procurement',
        'rfp',
        'request for proposal',
        'expression of interest',
    ],

    'monitored_countries' => [
        'DZ' => ['name' => 'Algeria', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'AO' => ['name' => 'Angola', 'region' => 'Africa', 'default_language_code' => 'pt'],
        'BJ' => ['name' => 'Benin', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'BW' => ['name' => 'Botswana', 'region' => 'Africa', 'default_language_code' => 'en'],
        'BF' => ['name' => 'Burkina Faso', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'BI' => ['name' => 'Burundi', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'CV' => ['name' => 'Cabo Verde', 'region' => 'Africa', 'default_language_code' => 'pt'],
        'CM' => ['name' => 'Cameroon', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'CF' => ['name' => 'Central African Republic', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'TD' => ['name' => 'Chad', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'KM' => ['name' => 'Comoros', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'CG' => ['name' => 'Congo', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'CI' => ['name' => "Cote d'Ivoire", 'region' => 'Africa', 'default_language_code' => 'fr'],
        'CD' => ['name' => 'Democratic Republic of the Congo', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'DJ' => ['name' => 'Djibouti', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'EG' => ['name' => 'Egypt', 'region' => 'Africa', 'default_language_code' => 'en'],
        'GQ' => ['name' => 'Equatorial Guinea', 'region' => 'Africa', 'default_language_code' => 'es'],
        'ER' => ['name' => 'Eritrea', 'region' => 'Africa', 'default_language_code' => 'en'],
        'SZ' => ['name' => 'Eswatini', 'region' => 'Africa', 'default_language_code' => 'en'],
        'ET' => ['name' => 'Ethiopia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'GA' => ['name' => 'Gabon', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'GM' => ['name' => 'Gambia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'GH' => ['name' => 'Ghana', 'region' => 'Africa', 'default_language_code' => 'en'],
        'GN' => ['name' => 'Guinea', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'GW' => ['name' => 'Guinea-Bissau', 'region' => 'Africa', 'default_language_code' => 'pt'],
        'KE' => ['name' => 'Kenya', 'region' => 'Africa', 'default_language_code' => 'en'],
        'LS' => ['name' => 'Lesotho', 'region' => 'Africa', 'default_language_code' => 'en'],
        'LR' => ['name' => 'Liberia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'LY' => ['name' => 'Libya', 'region' => 'Africa', 'default_language_code' => 'en'],
        'MG' => ['name' => 'Madagascar', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'MW' => ['name' => 'Malawi', 'region' => 'Africa', 'default_language_code' => 'en'],
        'ML' => ['name' => 'Mali', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'MR' => ['name' => 'Mauritania', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'MU' => ['name' => 'Mauritius', 'region' => 'Africa', 'default_language_code' => 'en'],
        'MA' => ['name' => 'Morocco', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'MZ' => ['name' => 'Mozambique', 'region' => 'Africa', 'default_language_code' => 'pt'],
        'NA' => ['name' => 'Namibia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'NE' => ['name' => 'Niger', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'NG' => ['name' => 'Nigeria', 'region' => 'Africa', 'default_language_code' => 'en'],
        'RW' => ['name' => 'Rwanda', 'region' => 'Africa', 'default_language_code' => 'en'],
        'SN' => ['name' => 'Senegal', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'SL' => ['name' => 'Sierra Leone', 'region' => 'Africa', 'default_language_code' => 'en'],
        'SO' => ['name' => 'Somalia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'ZA' => ['name' => 'South Africa', 'region' => 'Africa', 'default_language_code' => 'en'],
        'SS' => ['name' => 'South Sudan', 'region' => 'Africa', 'default_language_code' => 'en'],
        'SD' => ['name' => 'Sudan', 'region' => 'Africa', 'default_language_code' => 'en'],
        'TZ' => ['name' => 'Tanzania', 'region' => 'Africa', 'default_language_code' => 'en'],
        'TG' => ['name' => 'Togo', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'TN' => ['name' => 'Tunisia', 'region' => 'Africa', 'default_language_code' => 'fr'],
        'UG' => ['name' => 'Uganda', 'region' => 'Africa', 'default_language_code' => 'en'],
        'ZM' => ['name' => 'Zambia', 'region' => 'Africa', 'default_language_code' => 'en'],
        'ZW' => ['name' => 'Zimbabwe', 'region' => 'Africa', 'default_language_code' => 'en'],
        'AI' => ['name' => 'Anguilla', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'AG' => ['name' => 'Antigua and Barbuda', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'AW' => ['name' => 'Aruba', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'BS' => ['name' => 'Bahamas', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'BB' => ['name' => 'Barbados', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'BZ' => ['name' => 'Belize', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'BM' => ['name' => 'Bermuda', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'VG' => ['name' => 'British Virgin Islands', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'KY' => ['name' => 'Cayman Islands', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'CU' => ['name' => 'Cuba', 'region' => 'Caribbean', 'default_language_code' => 'es'],
        'CW' => ['name' => 'Curacao', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'DM' => ['name' => 'Dominica', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'DO' => ['name' => 'Dominican Republic', 'region' => 'Caribbean', 'default_language_code' => 'es'],
        'GD' => ['name' => 'Grenada', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'GP' => ['name' => 'Guadeloupe', 'region' => 'Caribbean', 'default_language_code' => 'fr'],
        'GY' => ['name' => 'Guyana', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'HT' => ['name' => 'Haiti', 'region' => 'Caribbean', 'default_language_code' => 'fr'],
        'JM' => ['name' => 'Jamaica', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'MQ' => ['name' => 'Martinique', 'region' => 'Caribbean', 'default_language_code' => 'fr'],
        'MS' => ['name' => 'Montserrat', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'PR' => ['name' => 'Puerto Rico', 'region' => 'Caribbean', 'default_language_code' => 'es'],
        'KN' => ['name' => 'Saint Kitts and Nevis', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'LC' => ['name' => 'Saint Lucia', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'VC' => ['name' => 'Saint Vincent and the Grenadines', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'SX' => ['name' => 'Sint Maarten', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'SR' => ['name' => 'Suriname', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'TT' => ['name' => 'Trinidad and Tobago', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'TC' => ['name' => 'Turks and Caicos Islands', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'VI' => ['name' => 'US Virgin Islands', 'region' => 'Caribbean', 'default_language_code' => 'en'],
        'AR' => [
            'name' => 'Argentina',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Administracion Nacional de la Seguridad Social',
            'search_names' => ['Argentina', 'ANSES', 'Administracion Nacional de la Seguridad Social'],
            'sources' => [
                ['name' => 'ANSES', 'domain' => 'anses.gob.ar', 'url' => 'https://www.anses.gob.ar/'],
                ['name' => 'Argentina Ministry of Labour', 'domain' => 'argentina.gob.ar', 'url' => 'https://www.argentina.gob.ar/trabajo'],
                ['name' => 'COMPR.AR Argentina Procurement', 'domain' => 'comprar.gob.ar', 'url' => 'https://comprar.gob.ar/'],
                ['name' => 'Telam Argentina', 'domain' => 'telam.com.ar', 'url' => 'https://www.telam.com.ar/'],
                ['name' => 'Ambito Argentina', 'domain' => 'ambito.com', 'url' => 'https://www.ambito.com/'],
            ],
        ],
        'BO' => [
            'name' => 'Bolivia',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Gestora Publica de la Seguridad Social de Largo Plazo',
            'search_names' => ['Bolivia', 'Gestora Publica', 'seguridad social Bolivia', 'pensiones Bolivia'],
            'sources' => [
                ['name' => 'Gestora Publica Bolivia', 'domain' => 'gestora.bo', 'url' => 'https://www.gestora.bo/'],
                ['name' => 'Autoridad de Fiscalizacion y Control de Pensiones y Seguros', 'domain' => 'aps.gob.bo', 'url' => 'https://www.aps.gob.bo/'],
                ['name' => 'SICOES Bolivia Procurement', 'domain' => 'sicoes.gob.bo', 'url' => 'https://www.sicoes.gob.bo/'],
                ['name' => 'ABI Bolivia', 'domain' => 'abi.bo', 'url' => 'https://www.abi.bo/'],
            ],
        ],
        'BR' => [
            'name' => 'Brazil',
            'region' => 'Latin America',
            'default_language_code' => 'pt',
            'social_security_administration_name' => 'Instituto Nacional do Seguro Social',
            'search_names' => ['Brazil', 'Brasil', 'INSS', 'Previdencia Social', 'Instituto Nacional do Seguro Social'],
            'sources' => [
                ['name' => 'INSS Brazil', 'domain' => 'gov.br', 'url' => 'https://www.gov.br/inss/'],
                ['name' => 'Brazil Ministry of Social Security', 'domain' => 'gov.br', 'url' => 'https://www.gov.br/previdencia/'],
                ['name' => 'Compras.gov.br Brazil Procurement', 'domain' => 'compras.gov.br', 'url' => 'https://www.gov.br/compras/'],
                ['name' => 'Agencia Brasil', 'domain' => 'agenciabrasil.ebc.com.br', 'url' => 'https://agenciabrasil.ebc.com.br/'],
            ],
        ],
        'CL' => [
            'name' => 'Chile',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto de Prevision Social',
            'search_names' => ['Chile', 'IPS Chile', 'Instituto de Prevision Social', 'Superintendencia de Pensiones'],
            'sources' => [
                ['name' => 'Instituto de Prevision Social Chile', 'domain' => 'ips.gob.cl', 'url' => 'https://www.ips.gob.cl/'],
                ['name' => 'Superintendencia de Pensiones Chile', 'domain' => 'spensiones.cl', 'url' => 'https://www.spensiones.cl/'],
                ['name' => 'ChileCompra Mercado Publico', 'domain' => 'mercadopublico.cl', 'url' => 'https://www.mercadopublico.cl/'],
                ['name' => 'BioBioChile', 'domain' => 'biobiochile.cl', 'url' => 'https://www.biobiochile.cl/'],
            ],
        ],
        'CO' => [
            'name' => 'Colombia',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Colpensiones',
            'search_names' => ['Colombia', 'Colpensiones', 'pensiones Colombia', 'seguridad social Colombia'],
            'sources' => [
                ['name' => 'Colpensiones', 'domain' => 'colpensiones.gov.co', 'url' => 'https://www.colpensiones.gov.co/'],
                ['name' => 'Colombia Ministry of Labour', 'domain' => 'mintrabajo.gov.co', 'url' => 'https://www.mintrabajo.gov.co/'],
                ['name' => 'SECOP Colombia Compra Eficiente', 'domain' => 'colombiacompra.gov.co', 'url' => 'https://www.colombiacompra.gov.co/secop'],
                ['name' => 'Portafolio Colombia', 'domain' => 'portafolio.co', 'url' => 'https://www.portafolio.co/'],
            ],
        ],
        'CR' => [
            'name' => 'Costa Rica',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Caja Costarricense de Seguro Social',
            'search_names' => ['Costa Rica', 'CCSS', 'Caja Costarricense de Seguro Social'],
            'sources' => [
                ['name' => 'Caja Costarricense de Seguro Social', 'domain' => 'ccss.sa.cr', 'url' => 'https://www.ccss.sa.cr/'],
                ['name' => 'SICOP Costa Rica Procurement', 'domain' => 'sicop.go.cr', 'url' => 'https://www.sicop.go.cr/'],
                ['name' => 'La Nacion Costa Rica', 'domain' => 'nacion.com', 'url' => 'https://www.nacion.com/'],
            ],
        ],
        'EC' => [
            'name' => 'Ecuador',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Ecuatoriano de Seguridad Social',
            'search_names' => ['Ecuador', 'IESS', 'Instituto Ecuatoriano de Seguridad Social'],
            'sources' => [
                ['name' => 'Instituto Ecuatoriano de Seguridad Social', 'domain' => 'iess.gob.ec', 'url' => 'https://www.iess.gob.ec/'],
                ['name' => 'SERCOP Ecuador Procurement', 'domain' => 'sercop.gob.ec', 'url' => 'https://www.sercop.gob.ec/'],
                ['name' => 'El Comercio Ecuador', 'domain' => 'elcomercio.com', 'url' => 'https://www.elcomercio.com/'],
            ],
        ],
        'SV' => [
            'name' => 'El Salvador',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Salvadoreno del Seguro Social',
            'search_names' => ['El Salvador', 'ISSS', 'Instituto Salvadoreno del Seguro Social'],
            'sources' => [
                ['name' => 'Instituto Salvadoreno del Seguro Social', 'domain' => 'isss.gob.sv', 'url' => 'https://www.isss.gob.sv/'],
                ['name' => 'COMPRASAL El Salvador', 'domain' => 'comprasal.gob.sv', 'url' => 'https://www.comprasal.gob.sv/'],
                ['name' => 'Diario El Salvador', 'domain' => 'diarioelsalvador.com', 'url' => 'https://diarioelsalvador.com/'],
            ],
        ],
        'GT' => [
            'name' => 'Guatemala',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Guatemalteco de Seguridad Social',
            'search_names' => ['Guatemala', 'IGSS', 'Instituto Guatemalteco de Seguridad Social'],
            'sources' => [
                ['name' => 'Instituto Guatemalteco de Seguridad Social', 'domain' => 'igssgt.org', 'url' => 'https://www.igssgt.org/'],
                ['name' => 'Guatecompras Guatemala', 'domain' => 'guatecompras.gt', 'url' => 'https://www.guatecompras.gt/'],
                ['name' => 'Prensa Libre Guatemala', 'domain' => 'prensalibre.com', 'url' => 'https://www.prensalibre.com/'],
            ],
        ],
        'HN' => [
            'name' => 'Honduras',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Hondureno de Seguridad Social',
            'search_names' => ['Honduras', 'IHSS', 'Instituto Hondureno de Seguridad Social'],
            'sources' => [
                ['name' => 'Instituto Hondureno de Seguridad Social', 'domain' => 'ihss.hn', 'url' => 'https://www.ihss.hn/'],
                ['name' => 'HonduCompras', 'domain' => 'honducompras.gob.hn', 'url' => 'https://www.honducompras.gob.hn/'],
                ['name' => 'La Prensa Honduras', 'domain' => 'laprensa.hn', 'url' => 'https://www.laprensa.hn/'],
            ],
        ],
        'MX' => [
            'name' => 'Mexico',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Mexicano del Seguro Social / ISSSTE',
            'search_names' => ['Mexico', 'Mexico', 'IMSS', 'ISSSTE', 'seguridad social Mexico'],
            'sources' => [
                ['name' => 'Instituto Mexicano del Seguro Social', 'domain' => 'imss.gob.mx', 'url' => 'https://www.imss.gob.mx/'],
                ['name' => 'ISSSTE Mexico', 'domain' => 'gob.mx', 'url' => 'https://www.gob.mx/issste'],
                ['name' => 'CompraNet Mexico', 'domain' => 'compranet.hacienda.gob.mx', 'url' => 'https://compranet.hacienda.gob.mx/'],
                ['name' => 'El Economista Mexico', 'domain' => 'eleconomista.com.mx', 'url' => 'https://www.eleconomista.com.mx/'],
            ],
        ],
        'NI' => [
            'name' => 'Nicaragua',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Nicaraguense de Seguridad Social',
            'search_names' => ['Nicaragua', 'INSS Nicaragua', 'Instituto Nicaraguense de Seguridad Social'],
            'sources' => [
                ['name' => 'Instituto Nicaraguense de Seguridad Social', 'domain' => 'inss.gob.ni', 'url' => 'https://www.inss.gob.ni/'],
                ['name' => 'NicaraguaCompra', 'domain' => 'nicaraguacompra.gob.ni', 'url' => 'https://www.nicaraguacompra.gob.ni/'],
                ['name' => 'La Prensa Nicaragua', 'domain' => 'laprensani.com', 'url' => 'https://www.laprensani.com/'],
            ],
        ],
        'PA' => [
            'name' => 'Panama',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Caja de Seguro Social Panama',
            'search_names' => ['Panama', 'Caja de Seguro Social Panama', 'CSS Panama'],
            'sources' => [
                ['name' => 'Caja de Seguro Social Panama', 'domain' => 'css.gob.pa', 'url' => 'https://www.css.gob.pa/'],
                ['name' => 'PanamaCompra', 'domain' => 'panamacompra.gob.pa', 'url' => 'https://www.panamacompra.gob.pa/'],
                ['name' => 'La Estrella de Panama', 'domain' => 'laestrella.com.pa', 'url' => 'https://www.laestrella.com.pa/'],
            ],
        ],
        'PY' => [
            'name' => 'Paraguay',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto de Prevision Social Paraguay',
            'search_names' => ['Paraguay', 'IPS Paraguay', 'Instituto de Prevision Social Paraguay'],
            'sources' => [
                ['name' => 'Instituto de Prevision Social Paraguay', 'domain' => 'ips.gov.py', 'url' => 'https://www.ips.gov.py/'],
                ['name' => 'DNCP Paraguay Procurement', 'domain' => 'contrataciones.gov.py', 'url' => 'https://www.contrataciones.gov.py/'],
                ['name' => 'ABC Color Paraguay', 'domain' => 'abc.com.py', 'url' => 'https://www.abc.com.py/'],
            ],
        ],
        'PE' => [
            'name' => 'Peru',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Oficina de Normalizacion Previsional',
            'search_names' => ['Peru', 'ONP Peru', 'Oficina de Normalizacion Previsional', 'EsSalud'],
            'sources' => [
                ['name' => 'ONP Peru', 'domain' => 'onp.gob.pe', 'url' => 'https://www.onp.gob.pe/'],
                ['name' => 'EsSalud Peru', 'domain' => 'essalud.gob.pe', 'url' => 'https://www.essalud.gob.pe/'],
                ['name' => 'SEACE Peru Procurement', 'domain' => 'seace.gob.pe', 'url' => 'https://www.seace.gob.pe/'],
                ['name' => 'Gestion Peru', 'domain' => 'gestion.pe', 'url' => 'https://gestion.pe/'],
            ],
        ],
        'UY' => [
            'name' => 'Uruguay',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Banco de Prevision Social',
            'search_names' => ['Uruguay', 'BPS Uruguay', 'Banco de Prevision Social'],
            'sources' => [
                ['name' => 'Banco de Prevision Social Uruguay', 'domain' => 'bps.gub.uy', 'url' => 'https://www.bps.gub.uy/'],
                ['name' => 'Compras Estatales Uruguay', 'domain' => 'comprasestatales.gub.uy', 'url' => 'https://www.comprasestatales.gub.uy/'],
                ['name' => 'El Observador Uruguay', 'domain' => 'elobservador.com.uy', 'url' => 'https://www.elobservador.com.uy/'],
            ],
        ],
        'VE' => [
            'name' => 'Venezuela',
            'region' => 'Latin America',
            'default_language_code' => 'es',
            'social_security_administration_name' => 'Instituto Venezolano de los Seguros Sociales',
            'search_names' => ['Venezuela', 'IVSS', 'Instituto Venezolano de los Seguros Sociales'],
            'sources' => [
                ['name' => 'Instituto Venezolano de los Seguros Sociales', 'domain' => 'ivss.gov.ve', 'url' => 'https://www.ivss.gov.ve/'],
                ['name' => 'Servicio Nacional de Contrataciones Venezuela', 'domain' => 'snc.gob.ve', 'url' => 'https://www.snc.gob.ve/'],
                ['name' => 'El Nacional Venezuela', 'domain' => 'elnacional.com', 'url' => 'https://www.elnacional.com/'],
            ],
        ],
        'CA' => [
            'name' => 'Canada',
            'region' => 'North America',
            'default_language_code' => 'en',
            'search_names' => ['Canada', 'CanadaBuys', 'Canadian public procurement', 'provincial procurement Canada'],
            'priority_queries' => [
                'Canada public procurement HRMS payroll',
                'Canada government tender risk management software',
                'Canada government tender budgeting software',
                'Canada public sector pension administration software',
            ],
            'sources' => [
                ['name' => 'CanadaBuys Tender Opportunities', 'domain' => 'canadabuys.canada.ca', 'url' => 'https://canadabuys.canada.ca/en/tender-opportunities', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'federal'],
                ['name' => 'Ontario Tenders Portal', 'domain' => 'ontariotenders.app.jaggaer.com', 'url' => 'https://ontariotenders.app.jaggaer.com/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'BC Bid', 'domain' => 'bcbid.gov.bc.ca', 'url' => 'https://www.bcbid.gov.bc.ca/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'MERX Canadian Public Tenders', 'domain' => 'merx.com', 'url' => 'https://www.merx.com/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'aggregator'],
                ['name' => 'Toronto Bids and Tenders', 'domain' => 'toronto.bidsandtenders.ca', 'url' => 'https://toronto.bidsandtenders.ca/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'local'],
            ],
        ],
        'US' => [
            'name' => 'United States',
            'region' => 'North America',
            'default_language_code' => 'en',
            'search_names' => ['United States', 'USA', 'US federal procurement', 'state procurement', 'local government procurement'],
            'priority_queries' => [
                'SAM.gov HRMS payroll opportunity',
                'SAM.gov pension administration software opportunity',
                'SAM.gov enterprise risk management software opportunity',
                'SAM.gov budgeting software opportunity',
                'state procurement HRMS payroll software',
                'local government procurement risk management software',
            ],
            'sources' => [
                ['name' => 'SAM.gov Contract Opportunities', 'domain' => 'sam.gov', 'url' => 'https://sam.gov/content/opportunities', 'access_method' => 'official_api', 'connector' => 'sam_gov_opportunities', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'federal'],
                ['name' => 'GSA Open APIs', 'domain' => 'open.gsa.gov', 'url' => 'https://open.gsa.gov/api/', 'access_method' => 'official_api_directory', 'connector' => 'gsa_api_directory', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'federal'],
                ['name' => 'USAspending.gov Awards API', 'domain' => 'usaspending.gov', 'url' => 'https://api.usaspending.gov/', 'access_method' => 'official_api', 'connector' => 'usaspending_awards', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'federal_awards'],
                ['name' => 'California Cal eProcure', 'domain' => 'caleprocure.ca.gov', 'url' => 'https://caleprocure.ca.gov/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'Texas Electronic State Business Daily', 'domain' => 'txsmartbuy.com', 'url' => 'https://www.txsmartbuy.com/esbd', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'New York State Contract Reporter', 'domain' => 'nyscr.ny.gov', 'url' => 'https://www.nyscr.ny.gov/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'Florida Vendor Bid System', 'domain' => 'myflorida.com', 'url' => 'https://vendor.myfloridamarketplace.com/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'Illinois BidBuy', 'domain' => 'bidbuy.illinois.gov', 'url' => 'https://bidbuy.illinois.gov/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'Pennsylvania eMarketplace', 'domain' => 'emarketplace.state.pa.us', 'url' => 'https://www.emarketplace.state.pa.us/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'state_provincial'],
                ['name' => 'New York City PASSPort', 'domain' => 'passport.cityofnewyork.us', 'url' => 'https://passport.cityofnewyork.us/page.aspx/en/rfp/request_browse_public', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'local'],
                ['name' => 'City of Chicago Procurement', 'domain' => 'chicago.gov', 'url' => 'https://www.chicago.gov/city/en/depts/dps.html', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'local'],
                ['name' => 'City of Houston Strategic Procurement', 'domain' => 'houstontx.gov', 'url' => 'https://www.houstontx.gov/bizwithhou/', 'source_class' => 'central_tender_portal', 'procurement_portal_type' => 'local'],
            ],
        ],
        'AL' => ['name' => 'Albania', 'region' => 'Europe', 'default_language_code' => 'sq'],
        'AD' => ['name' => 'Andorra', 'region' => 'Europe', 'default_language_code' => 'ca'],
        'AT' => ['name' => 'Austria', 'region' => 'Europe', 'default_language_code' => 'de'],
        'BE' => ['name' => 'Belgium', 'region' => 'Europe', 'default_language_code' => 'fr', 'search_names' => ['Belgium', 'Belgique', 'Belgie']],
        'BA' => ['name' => 'Bosnia and Herzegovina', 'region' => 'Europe', 'default_language_code' => 'bs'],
        'BG' => ['name' => 'Bulgaria', 'region' => 'Europe', 'default_language_code' => 'bg'],
        'HR' => ['name' => 'Croatia', 'region' => 'Europe', 'default_language_code' => 'hr'],
        'CY' => ['name' => 'Cyprus', 'region' => 'Europe', 'default_language_code' => 'el'],
        'CZ' => ['name' => 'Czechia', 'region' => 'Europe', 'default_language_code' => 'cs', 'search_names' => ['Czechia', 'Czech Republic']],
        'DK' => ['name' => 'Denmark', 'region' => 'Europe', 'default_language_code' => 'da'],
        'EE' => ['name' => 'Estonia', 'region' => 'Europe', 'default_language_code' => 'et'],
        'FI' => ['name' => 'Finland', 'region' => 'Europe', 'default_language_code' => 'fi'],
        'FR' => ['name' => 'France', 'region' => 'Europe', 'default_language_code' => 'fr'],
        'DE' => ['name' => 'Germany', 'region' => 'Europe', 'default_language_code' => 'de', 'search_names' => ['Germany', 'Deutschland']],
        'GR' => ['name' => 'Greece', 'region' => 'Europe', 'default_language_code' => 'el'],
        'HU' => ['name' => 'Hungary', 'region' => 'Europe', 'default_language_code' => 'hu'],
        'IS' => ['name' => 'Iceland', 'region' => 'Europe', 'default_language_code' => 'is'],
        'IE' => ['name' => 'Ireland', 'region' => 'Europe', 'default_language_code' => 'en'],
        'IT' => ['name' => 'Italy', 'region' => 'Europe', 'default_language_code' => 'it'],
        'XK' => ['name' => 'Kosovo', 'region' => 'Europe', 'default_language_code' => 'sq'],
        'LV' => ['name' => 'Latvia', 'region' => 'Europe', 'default_language_code' => 'lv'],
        'LI' => ['name' => 'Liechtenstein', 'region' => 'Europe', 'default_language_code' => 'de'],
        'LT' => ['name' => 'Lithuania', 'region' => 'Europe', 'default_language_code' => 'lt'],
        'LU' => ['name' => 'Luxembourg', 'region' => 'Europe', 'default_language_code' => 'fr'],
        'MT' => ['name' => 'Malta', 'region' => 'Europe', 'default_language_code' => 'en'],
        'MD' => ['name' => 'Moldova', 'region' => 'Europe', 'default_language_code' => 'ro'],
        'MC' => ['name' => 'Monaco', 'region' => 'Europe', 'default_language_code' => 'fr'],
        'ME' => ['name' => 'Montenegro', 'region' => 'Europe', 'default_language_code' => 'sr'],
        'NL' => ['name' => 'Netherlands', 'region' => 'Europe', 'default_language_code' => 'nl', 'search_names' => ['Netherlands', 'Nederland']],
        'MK' => ['name' => 'North Macedonia', 'region' => 'Europe', 'default_language_code' => 'mk'],
        'NO' => ['name' => 'Norway', 'region' => 'Europe', 'default_language_code' => 'no'],
        'PL' => ['name' => 'Poland', 'region' => 'Europe', 'default_language_code' => 'pl'],
        'PT' => ['name' => 'Portugal', 'region' => 'Europe', 'default_language_code' => 'pt'],
        'RO' => ['name' => 'Romania', 'region' => 'Europe', 'default_language_code' => 'ro'],
        'SM' => ['name' => 'San Marino', 'region' => 'Europe', 'default_language_code' => 'it'],
        'RS' => ['name' => 'Serbia', 'region' => 'Europe', 'default_language_code' => 'sr'],
        'SK' => ['name' => 'Slovakia', 'region' => 'Europe', 'default_language_code' => 'sk'],
        'SI' => ['name' => 'Slovenia', 'region' => 'Europe', 'default_language_code' => 'sl'],
        'ES' => ['name' => 'Spain', 'region' => 'Europe', 'default_language_code' => 'es'],
        'SE' => ['name' => 'Sweden', 'region' => 'Europe', 'default_language_code' => 'sv'],
        'CH' => ['name' => 'Switzerland', 'region' => 'Europe', 'default_language_code' => 'de', 'search_names' => ['Switzerland', 'Suisse', 'Schweiz', 'Svizzera']],
        'UA' => ['name' => 'Ukraine', 'region' => 'Europe', 'default_language_code' => 'uk'],
        'GB' => ['name' => 'United Kingdom', 'region' => 'Europe', 'default_language_code' => 'en', 'search_names' => ['United Kingdom', 'UK', 'Great Britain']],
        'VA' => ['name' => 'Vatican City', 'region' => 'Europe', 'default_language_code' => 'it'],
        'AF' => ['name' => 'Afghanistan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'AM' => ['name' => 'Armenia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'AZ' => ['name' => 'Azerbaijan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'BH' => ['name' => 'Bahrain', 'region' => 'Asia', 'default_language_code' => 'en'],
        'BD' => ['name' => 'Bangladesh', 'region' => 'Asia', 'default_language_code' => 'en'],
        'BT' => ['name' => 'Bhutan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'BN' => ['name' => 'Brunei', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KH' => ['name' => 'Cambodia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'CN' => ['name' => 'China', 'region' => 'Asia', 'default_language_code' => 'en'],
        'GE' => ['name' => 'Georgia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'IN' => ['name' => 'India', 'region' => 'Asia', 'default_language_code' => 'en'],
        'ID' => ['name' => 'Indonesia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'IR' => ['name' => 'Iran', 'region' => 'Asia', 'default_language_code' => 'en'],
        'IQ' => ['name' => 'Iraq', 'region' => 'Asia', 'default_language_code' => 'en'],
        'IL' => ['name' => 'Israel', 'region' => 'Asia', 'default_language_code' => 'en'],
        'JP' => ['name' => 'Japan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'JO' => ['name' => 'Jordan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KZ' => ['name' => 'Kazakhstan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KW' => ['name' => 'Kuwait', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KG' => ['name' => 'Kyrgyzstan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'LA' => ['name' => 'Laos', 'region' => 'Asia', 'default_language_code' => 'en'],
        'LB' => ['name' => 'Lebanon', 'region' => 'Asia', 'default_language_code' => 'en'],
        'MY' => ['name' => 'Malaysia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'MV' => ['name' => 'Maldives', 'region' => 'Asia', 'default_language_code' => 'en'],
        'MN' => ['name' => 'Mongolia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'MM' => ['name' => 'Myanmar', 'region' => 'Asia', 'default_language_code' => 'en'],
        'NP' => ['name' => 'Nepal', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KP' => ['name' => 'North Korea', 'region' => 'Asia', 'default_language_code' => 'en'],
        'OM' => ['name' => 'Oman', 'region' => 'Asia', 'default_language_code' => 'en'],
        'PK' => ['name' => 'Pakistan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'PS' => ['name' => 'Palestine', 'region' => 'Asia', 'default_language_code' => 'en'],
        'PH' => ['name' => 'Philippines', 'region' => 'Asia', 'default_language_code' => 'en'],
        'QA' => ['name' => 'Qatar', 'region' => 'Asia', 'default_language_code' => 'en'],
        'SA' => ['name' => 'Saudi Arabia', 'region' => 'Asia', 'default_language_code' => 'en'],
        'SG' => ['name' => 'Singapore', 'region' => 'Asia', 'default_language_code' => 'en'],
        'KR' => ['name' => 'South Korea', 'region' => 'Asia', 'default_language_code' => 'en'],
        'LK' => ['name' => 'Sri Lanka', 'region' => 'Asia', 'default_language_code' => 'en'],
        'SY' => ['name' => 'Syria', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TW' => ['name' => 'Taiwan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TJ' => ['name' => 'Tajikistan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TH' => ['name' => 'Thailand', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TL' => ['name' => 'Timor-Leste', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TR' => ['name' => 'Turkey', 'region' => 'Asia', 'default_language_code' => 'en'],
        'TM' => ['name' => 'Turkmenistan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'AE' => ['name' => 'United Arab Emirates', 'region' => 'Asia', 'default_language_code' => 'en'],
        'UZ' => ['name' => 'Uzbekistan', 'region' => 'Asia', 'default_language_code' => 'en'],
        'VN' => ['name' => 'Vietnam', 'region' => 'Asia', 'default_language_code' => 'en'],
        'YE' => ['name' => 'Yemen', 'region' => 'Asia', 'default_language_code' => 'en'],
    ],

    'countries' => [
        'AG' => [
            'name' => 'Antigua and Barbuda',
            'iso_code' => 'AG',
            'region' => 'Caribbean',
            'default_language_code' => 'en',
            'social_security_administration_name' => 'Antigua and Barbuda Social Security Board',
            'search_names' => ['Antigua and Barbuda', 'Antigua', 'Barbuda', 'ABSSB'],
            'priority_queries' => [
                'Antigua ABSSB pension',
                '"Antigua and Barbuda" "Social Security Board"',
                '"Antigua and Barbuda" pension contribution',
            ],
            'sources' => [
                ['name' => 'Antigua and Barbuda Social Security Board', 'domain' => 'socialsecurity.gov.ag', 'url' => 'https://socialsecurity.gov.ag/', 'type' => 'wordpress'],
                ['name' => 'Antigua and Barbuda Tenders Board', 'domain' => 'tendersboard.gov.ag', 'url' => 'https://tendersboard.gov.ag/'],
                ['name' => 'Government of Antigua and Barbuda', 'domain' => 'ab.gov.ag', 'url' => 'https://ab.gov.ag/'],
                ['name' => 'Antigua and Barbuda Laws', 'domain' => 'laws.gov.ag', 'url' => 'https://laws.gov.ag/'],
                ['name' => 'ABS TV Radio', 'domain' => 'abstvradio.com', 'url' => 'https://abstvradio.com/'],
                ['name' => 'Antigua Observer', 'domain' => 'antiguaobserver.com', 'url' => 'https://antiguaobserver.com/'],
                ['name' => 'Antigua News Room', 'domain' => 'antiguanewsroom.com', 'url' => 'https://antiguanewsroom.com/'],
                ['name' => 'Pointville Communications', 'domain' => 'pointville.ag', 'url' => 'https://pointville.ag/'],
            ],
        ],

        'BS' => [
            'social_security_administration_name' => 'National Insurance Board of The Bahamas',
            'search_names' => ['Bahamas', 'The Bahamas', 'National Insurance Board Bahamas', 'NIB Bahamas'],
            'priority_queries' => [
                'Bahamas National Insurance Board pension',
                'Bahamas NIB public tenders',
                'Bahamas social security pension reform',
                'Bahamas public procurement payroll HRMS',
            ],
            'sources' => [
                ['name' => 'National Insurance Board of The Bahamas', 'domain' => 'nib-bahamas.com', 'url' => 'https://www.nib-bahamas.com/'],
                ['name' => 'National Insurance Board Public Tenders', 'domain' => 'nib-bahamas.com', 'url' => 'https://www.nib-bahamas.com/public-tenders/'],
                ['name' => 'Government of The Bahamas', 'domain' => 'bahamas.gov.bs', 'url' => 'https://www.bahamas.gov.bs/'],
                ['name' => 'The Nassau Guardian', 'domain' => 'thenassauguardian.com', 'url' => 'https://thenassauguardian.com/'],
                ['name' => 'The Tribune', 'domain' => 'tribune242.com', 'url' => 'https://www.tribune242.com/'],
                ['name' => 'Eyewitness News Bahamas', 'domain' => 'ewnews.com', 'url' => 'https://ewnews.com/'],
                ['name' => 'Bahamas Local', 'domain' => 'bahamaslocal.com', 'url' => 'https://www.bahamaslocal.com/'],
            ],
        ],

        'BB' => [
            'social_security_administration_name' => 'National Insurance and Social Security Service',
            'search_names' => ['Barbados', 'National Insurance and Social Security Service', 'NIS Barbados', 'NISS Barbados'],
            'priority_queries' => [
                'Barbados NIS pension',
                'Barbados social security contributions',
                'Barbados government procurement HRMS payroll',
                'Barbados pension reform',
            ],
            'sources' => [
                ['name' => 'National Insurance and Social Security Service', 'domain' => 'nis.gov.bb', 'url' => 'https://www.nis.gov.bb/'],
                ['name' => 'Government Procurement Department Barbados', 'domain' => 'procure.gov.bb', 'url' => 'https://procure.gov.bb/'],
                ['name' => 'Barbados Government Information Service', 'domain' => 'gisbarbados.gov.bb', 'url' => 'https://gisbarbados.gov.bb/'],
                ['name' => 'Barbados Today', 'domain' => 'barbadostoday.bb', 'url' => 'https://barbadostoday.bb/'],
                ['name' => 'Nation News', 'domain' => 'nationnews.com', 'url' => 'https://www.nationnews.com/'],
                ['name' => 'Barbados Business Journal', 'domain' => 'barbadosbusinessjournal.com', 'url' => 'https://www.barbadosbusinessjournal.com/'],
            ],
        ],

        'DM' => [
            'social_security_administration_name' => 'Dominica Social Security',
            'search_names' => ['Dominica', 'Dominica Social Security', 'DSS Dominica'],
            'priority_queries' => [
                'Dominica Social Security pension',
                'Dominica social security contributions',
                'Dominica procurement HRMS payroll',
                'Dominica pension reform',
            ],
            'sources' => [
                ['name' => 'Dominica Social Security', 'domain' => 'dss.dm', 'url' => 'https://www.dss.dm/'],
                ['name' => 'Central Procurement Unit Dominica', 'domain' => 'finance.gov.dm', 'url' => 'https://finance.gov.dm/en/about/divisions-units-and-departments/central-procurement-unit'],
                ['name' => 'Government of Dominica', 'domain' => 'dominica.gov.dm', 'url' => 'https://dominica.gov.dm/'],
                ['name' => 'Dominica News Online', 'domain' => 'dominicanewsonline.com', 'url' => 'https://dominicanewsonline.com/'],
                ['name' => 'Emo News Dominica', 'domain' => 'emonewsdm.com', 'url' => 'https://emonewsdm.com/'],
            ],
        ],

        'GD' => [
            'social_security_administration_name' => 'National Insurance Scheme Grenada',
            'search_names' => ['Grenada', 'National Insurance Scheme Grenada', 'NIS Grenada'],
            'priority_queries' => [
                'Grenada NIS pension',
                'Grenada National Insurance Scheme contribution',
                'Grenada procurement HRMS payroll',
                'Grenada pension reform',
            ],
            'sources' => [
                ['name' => 'National Insurance Scheme Grenada', 'domain' => 'nisgrenada.org', 'url' => 'https://nisgrenada.org/'],
                ['name' => 'Grenada Public Procurement', 'domain' => 'procurement.gov.gd', 'url' => 'https://procurement.gov.gd/'],
                ['name' => 'Government of Grenada', 'domain' => 'gov.gd', 'url' => 'https://www.gov.gd/'],
                ['name' => 'NOW Grenada', 'domain' => 'nowgrenada.com', 'url' => 'https://nowgrenada.com/'],
                ['name' => 'The New Today Grenada', 'domain' => 'thenewtodaygrenada.com', 'url' => 'https://www.thenewtodaygrenada.com/'],
                ['name' => 'Grenada Informer', 'domain' => 'thegrenadainformer.com', 'url' => 'https://thegrenadainformer.com/'],
            ],
        ],

        'LC' => [
            'social_security_administration_name' => 'National Insurance Corporation Saint Lucia',
            'search_names' => ['Saint Lucia', 'St Lucia', 'National Insurance Corporation Saint Lucia', 'NIC Saint Lucia'],
            'priority_queries' => [
                'Saint Lucia NIC pension',
                'St Lucia National Insurance Corporation RFP',
                'Saint Lucia procurement HRMS payroll',
                'Saint Lucia pension reform',
            ],
            'sources' => [
                ['name' => 'National Insurance Corporation Saint Lucia', 'domain' => 'stlucianic.org', 'url' => 'https://www.stlucianic.org/'],
                ['name' => 'National Insurance Corporation Saint Lucia RFPs', 'domain' => 'stlucianic.org', 'url' => 'https://www.stlucianic.org/?s=RFP'],
                ['name' => 'Government of Saint Lucia', 'domain' => 'govt.lc', 'url' => 'https://www.govt.lc/'],
                ['name' => 'Government Information Service Saint Lucia', 'domain' => 'archive.stlucia.gov.lc', 'url' => 'https://archive.stlucia.gov.lc/gis/'],
                ['name' => 'Saint Lucia Government Gazette', 'domain' => 'npc.govt.lc', 'url' => 'https://npc.govt.lc/gazettes'],
                ['name' => 'St Lucia Times', 'domain' => 'stluciatimes.com', 'url' => 'https://stluciatimes.com/'],
                ['name' => 'The Voice Saint Lucia', 'domain' => 'thevoiceslu.com', 'url' => 'https://thevoiceslu.com/'],
                ['name' => 'The Star Saint Lucia', 'domain' => 'stluciastar.com', 'url' => 'https://stluciastar.com/'],
            ],
        ],

        'VC' => [
            'social_security_administration_name' => 'National Insurance Services St. Vincent and the Grenadines',
            'search_names' => ['Saint Vincent and the Grenadines', 'St Vincent and the Grenadines', 'NIS SVG', 'National Insurance Services SVG'],
            'priority_queries' => [
                'St Vincent NIS pension',
                'St Vincent National Insurance Services procurement',
                'SVG procurement HRMS payroll',
                'Saint Vincent pension reform',
            ],
            'sources' => [
                ['name' => 'National Insurance Services St. Vincent and the Grenadines', 'domain' => 'nissvg.org', 'url' => 'https://www.nissvg.org/'],
                ['name' => 'NIS SVG Requests for Expression of Interest', 'domain' => 'nissvg.org', 'url' => 'https://www.nissvg.org/rfeoi/'],
                ['name' => 'Government of Saint Vincent and the Grenadines Procurement Notices', 'domain' => 'gov.vc', 'url' => 'https://www.gov.vc/index.php/procurement-notices'],
                ['name' => 'Government of Saint Vincent and the Grenadines', 'domain' => 'gov.vc', 'url' => 'https://www.gov.vc/'],
                ['name' => 'iWitness News SVG', 'domain' => 'iwnsvg.com', 'url' => 'https://www.iwnsvg.com/'],
                ['name' => 'St. Vincent Times', 'domain' => 'stvincenttimes.com', 'url' => 'https://www.stvincenttimes.com/'],
            ],
        ],

        'TT' => [
            'social_security_administration_name' => 'National Insurance Board of Trinidad and Tobago',
            'search_names' => ['Trinidad and Tobago', 'Trinidad', 'Tobago', 'NIBTT', 'National Insurance Board Trinidad and Tobago'],
            'priority_queries' => [
                'Trinidad NIBTT pension',
                'Trinidad and Tobago National Insurance Board procurement',
                'Trinidad HRMS tender payroll',
                'Trinidad pension reform',
            ],
            'sources' => [
                ['name' => 'National Insurance Board of Trinidad and Tobago', 'domain' => 'nibtt.net', 'url' => 'https://www.nibtt.net/'],
                ['name' => 'Ministry of Finance Trinidad and Tobago', 'domain' => 'finance.gov.tt', 'url' => 'https://www.finance.gov.tt/'],
                ['name' => 'Trinidad and Tobago Ministry of Finance Procurement Notices', 'domain' => 'finance.gov.tt', 'url' => 'https://www.finance.gov.tt/divisions/procurement-unit/notices/'],
                ['name' => 'Office of Procurement Regulation Trinidad and Tobago', 'domain' => 'oprtt.org', 'url' => 'https://oprtt.org/'],
                ['name' => 'Ministry of Social Development and Family Services Procurement', 'domain' => 'social.gov.tt', 'url' => 'https://www.social.gov.tt/procurement-unit/'],
                ['name' => 'Trinidad and Tobago Newsday', 'domain' => 'newsday.co.tt', 'url' => 'https://newsday.co.tt/'],
                ['name' => 'Trinidad and Tobago Guardian', 'domain' => 'guardian.co.tt', 'url' => 'https://www.guardian.co.tt/'],
                ['name' => 'Loop News Trinidad and Tobago', 'domain' => 'loopnews.com', 'url' => 'https://tt.loopnews.com/'],
                ['name' => 'CNC3 Trinidad and Tobago', 'domain' => 'cnc3.co.tt', 'url' => 'https://www.cnc3.co.tt/'],
                ['name' => 'Island Tenders Trinidad and Tobago', 'domain' => 'islandtenders.com', 'url' => 'https://islandtenders.com/'],
            ],
        ],

        'SN' => [
            'name' => 'Senegal',
            'iso_code' => 'SN',
            'region' => 'Africa',
            'default_language_code' => 'fr',
            'social_security_administration_name' => 'Institution de Prevoyance Retraite du Senegal / Caisse de Securite Sociale',
            'search_names' => ['Senegal', 'Sénégal', 'IPRES', 'CSS Senegal', 'Caisse de Sécurité Sociale Sénégal'],
            'priority_queries' => [
                'Senegal IPRES',
                'Sénégal IPRES',
                'Senegal "Caisse de Sécurité Sociale"',
                'IPRES CSS "protection sociale"',
                'IPRES CSS retraite',
                'IPRES CSS tender',
                'IPRES CSS procurement',
            ],
            'sources' => [
                ['name' => 'Direction Generale du Travail et de la Securite Sociale', 'domain' => 'dgtss.gouv.sn', 'url' => 'https://dgtss.gouv.sn/'],
                ['name' => 'Ministere du Travail du Senegal', 'domain' => 'travail.gouv.sn', 'url' => 'https://travail.gouv.sn/'],
                ['name' => 'IPRES', 'domain' => 'ipres.sn', 'url' => 'https://www.ipres.sn/'],
                ['name' => 'Caisse de Securite Sociale / NDAMLI', 'domain' => 'secusociale.sn', 'url' => 'https://online.secusociale.sn/'],
                ['name' => 'Agence de Presse Senegalaise', 'domain' => 'aps.sn', 'url' => 'https://aps.sn/'],
                ['name' => 'Seneweb', 'domain' => 'seneweb.com', 'url' => 'https://www.seneweb.com/'],
                ['name' => 'Dakaractu', 'domain' => 'dakaractu.com', 'url' => 'https://www.dakaractu.com/'],
                ['name' => 'Le Quotidien', 'domain' => 'lequotidien.sn', 'url' => 'https://lequotidien.sn/'],
                ['name' => 'Le Soleil', 'domain' => 'lesoleil.sn', 'url' => 'https://lesoleil.sn/'],
                ['name' => 'SenOffre', 'domain' => 'senoffre.com', 'url' => 'https://senoffre.com/'],
            ],
        ],

        'BM' => [
            'sources' => [
                ['name' => 'Government of Bermuda Procurement', 'domain' => 'gov.bm', 'url' => 'https://www.gov.bm/procurement'],
                ['name' => 'Government of Bermuda', 'domain' => 'gov.bm', 'url' => 'https://www.gov.bm/'],
                ['name' => 'The Royal Gazette Bermuda', 'domain' => 'royalgazette.com', 'url' => 'https://www.royalgazette.com/'],
                ['name' => 'Bernews', 'domain' => 'bernews.com', 'url' => 'https://bernews.com/'],
            ],
            'priority_queries' => [
                'Bermuda HRMS tender',
                'Bermuda HRIMS procurement',
                'Bermuda payroll RFP',
                'site:gov.bm/procurement HRIMS',
            ],
            'known_items' => [
                'hrms_tenders' => [
                    [
                        'title' => 'Human Resource Information Management System (HRIMS)',
                        'source_name' => 'Government of Bermuda Procurement',
                        'source_url' => 'https://www.gov.bm/procurement/human-resource-information-management-system-hrims',
                        'publication_date' => '2024-11-18',
                        'summary' => 'The Department of Employee and Organizational Development sought proposals for a fully integrated Human Resource Information Management System (HRIMS) covering HR, payroll, benefits administration, recruitment, performance management, learning management, and workforce analytics.',
                        'relevance_score' => 8.50,
                    ],
                ],
            ],
        ],

        'JM' => [
            'social_security_administration_name' => 'National Insurance Scheme Jamaica',
            'search_names' => ['Jamaica', 'National Insurance Scheme Jamaica', 'NIS Jamaica', 'Ministry of Labour and Social Security Jamaica'],
            'sources' => [
                ['name' => 'Ministry of Labour and Social Security Jamaica', 'domain' => 'mlss.gov.jm', 'url' => 'https://www.mlss.gov.jm/'],
                ['name' => 'Government of Jamaica Electronic Procurement', 'domain' => 'gojep.gov.jm', 'url' => 'https://www.gojep.gov.jm/'],
                ['name' => 'Jamaica Public Procurement Commission', 'domain' => 'ppc.gov.jm', 'url' => 'https://www.ppc.gov.jm/'],
                ['name' => 'Jamaica Information Service', 'domain' => 'jis.gov.jm', 'url' => 'https://jis.gov.jm/'],
                ['name' => 'Jamaica Gleaner', 'domain' => 'jamaica-gleaner.com', 'url' => 'https://jamaica-gleaner.com/'],
                ['name' => 'Jamaica Observer', 'domain' => 'jamaicaobserver.com', 'url' => 'https://www.jamaicaobserver.com/'],
                ['name' => 'Radio Jamaica News', 'domain' => 'radiojamaicanewsonline.com', 'url' => 'https://radiojamaicanewsonline.com/'],
            ],
            'priority_queries' => [
                'Jamaica HRMS tender',
                'Jamaica payroll RFP',
                'Jamaica human resources management system procurement',
                'GOJEP HRMS payroll',
            ],
        ],
    ],
];
